/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package coin;
import java.util.Arrays;


public class Change {
    private int[] changeGiven;
    private int amount;
    private int coins[];

    Change(int amount, int coins[]){
        this.amount = amount;
        this.coins = coins;
        this.changeGiven = new int[coins.length];
    }

    public int[] workoutChange(){
        this.regularway();
        this.oneCoin();
        return this.changeGiven;
    }

    private void regularway(){
        int i = 0, temp = this.amount;
        while(i < this.coins.length){
            if(temp - this.coins[i] >= 0){
                temp -= this.coins[i];
                this.changeGiven[i]++;
            }else{
                i++;
            }
        }
    }

    private void oneCoin(){
        int i = 0, temp = this.amount;
        while(i < this.coins.length){
            if(temp % this.coins[i] == 0 && temp/this.coins[i] < Arrays.stream(this.changeGiven).sum()){
                Arrays.fill(this.changeGiven, 0);
                this.changeGiven[i] = temp/this.coins[i];
            }else{
                i++;
            }
        }    
    }

}
