/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package coin;

public class Change {
    private Integer[] changeGiven = {0, 0, 0};
    private int amount;

    public Integer[] workoutChange(int amount){
        this.amount = amount;
        this.multipleOfThreeAndNotFour();
        this.normalChange();
        return this.changeGiven;
    }

    private void multipleOfThreeAndNotFour(){
        if(this.amount % 3 == 0 && this.amount % 4 != 0){
            int temp = this.amount / 3;
            changeGiven[1] = temp;
            this.amount = 0;
        }
    }

    private void normalChange(){
        int i = 0; 
        while(i < this.changeGiven.length){
            if(this.amount - Coins.coins[i] >= 0){
                this.amount -= Coins.coins[i];
                this.changeGiven[i] += 1;
            }else{
                i++;
            }
        }
    }
}
