/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package coin;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void givesCorrectChangefor1() {
        Change classUnderTest = new Change();
        Integer[] expected = {0, 0, 1};
        assertArrayEquals(classUnderTest.workoutChange(1), expected);
    }
    @Test void givesCorrectChangefor5() {
        Change classUnderTest = new Change();
        Integer[] expected = {1, 0, 1};
        assertArrayEquals(classUnderTest.workoutChange(5), expected);
    }
    @Test void givesCorrectChangefor6() {
        Change classUnderTest = new Change();
        Integer[] expected = {0, 2, 0};
        assertArrayEquals(classUnderTest.workoutChange(6), expected);
    }
    @Test void givesCorrectChangefor12() {
        Change classUnderTest = new Change();
        Integer[] expected = {3, 0, 0};
        assertArrayEquals(classUnderTest.workoutChange(12), expected);
    }
    @Test void givesCorrectChangefor17() {
        Change classUnderTest = new Change();
        Integer[] expected = {4, 0, 1};
        assertArrayEquals(classUnderTest.workoutChange(17), expected);
    }
}
